on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        
        with:
          message: 'Example of message !'
          GITHUB_TOKEN: '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'
